CREATE TABLE comunity.users (
    user_id int8 GENERATED BY DEFAULT AS IDENTITY( INCREMENT BY 1 MINVALUE 1 MAXVALUE 9223372036854775807 START 1 CACHE 1 NO CYCLE) NOT NULL,
    user_createdat timestamp(6) NOT NULL,
    user_email varchar(255) NOT NULL,
    user_password varchar(255) NOT NULL,
    user_status varchar(255) NOT NULL,
    user_username varchar(255) NOT NULL,
    CONSTRAINT users_ukey_email UNIQUE (user_email),
    CONSTRAINT users_ukey_username UNIQUE (user_username),
    CONSTRAINT users_pkey PRIMARY KEY (user_id)
);